export const skills = [
    "HTML",
    "CSS",
    "CSS Flexbox",
    "CSS Grid",
    "CSS BEM Convention",
    "Javascript",
    "Error handling",
    "Responsive Web Design",
    "Immutability",
    "NPM",
    "DOM",
    "Git",
    "Github Pull Requests & Review",
    "React",
    "React-dom",
    "React Hooks",
    "React-router",
    "React-redux",
    "Redux-toolkit",
    "Redux-saga",
    "Working with API (fetch, axios)",
    "Promises, Async/await",
    "Markdown",
    "Debugging",
    "Scrum",
    "Trello",
    "Teamwork",
];

export const nextSkills = [
"JS classes",
"Unit testing",
"Node.js",
"TypeScript",
"Cypress",
"React Context",
];